### ISSUE TITLE
Horse Mod v1.0 Roadmap

### ISSUE THREAD

**Issue by gjpeebles** [gjpeebles/Stardew-Valley-Mods#1]
# Summary

We want the first version to have a quest that starts at some point after you get a horse. The witch will turn your horse into a Void horse. You need to find help, and eventually gain the ability to change your horse's body and mane colors.

# Quest
- [x] Void horse
  - [ ] details...
- [ ] Help from Marnie
- [ ] Help from Wizard
- [ ] Help from Crops Fairy
- [ ] Help from Horse Fairy

# Art

# Code/Features
- [x] Discover how quest structure and interaction works
- [ ] Colorize desaturated textures
- [ ] Overlay multiple textures to create a composite
